pip install scipy
pip install mutagen
pip install praat-parselmouth
pip install matplotlib
pip install pandas
pip install librosa
pip install noisereduce
pip install jupyter
pip install setuptools
pip install torch
pip install xgboost
pip install sklearn
pip install numpy
